name: Run grit patterns test

env:
  OPENAI_API_KEY: invalid-openai-token
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16,18.x,20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install @getgrit/launcher
      run: npm install -g @getgrit/launcher

    - name: Run grit patterns test
      run: npx grit patterns test
